apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - crds.yaml
  - common.yaml
  - operator.yaml
images:
  - name: rook/ceph
    newTag: v1.19.2@sha256:944a1dd704968cfe8141598cd8df4f30ade304414e170b61c711298f9c9bb9a2
