apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
patches:
  - target:
      group: rbac.authorization.k8s.io
      version: v1
      kind: ClusterRole
      name: rook-ceph-system
    patch: |-
      op: add
      path: /rules/-
      value:
        apiGroups: ["monitoring.coreos.com"]
        resources: ["servicemonitors"]
        verbs: ["get"]
configMapGenerator:
  - name: rook-ceph-operator-config
    behavior: merge
    literals:
      - ROOK_CSI_ENABLE_GRPC_METRICS="true"
